### ISSUE TITLE
UnpicklingError when loading standard COCO model

### ISSUE THREAD

**Issue by kittentronic** [michhar/pytorch-yolo-v3-custom#13]
I'm trying to get going with this (very helpful-looking!) repo and as a first step wanted to test `live.py` with the reference COCO model. To do this I've downloaded `yolov3.weights` from pjreddie.com into the repo folder, and `coco.data` and `coco.names` from https://github.com/pjreddie/darknet/tree/master/ into the `cfg` and `data` folders respectively. On trying to run `live.py` I get:

```
(torchx) D:\path\to\repo>python live.py --source 0
Loading network.....
{'type': 'net', 'batch': '16', 'subdivisions': '1', 'width': '416', 'height': '416', 'channels': '3', 'momentum': '0.9', 'decay': '0.0005', 'angle': '0', 'saturation': '1.5', 'exposure': '1.5', 'hue': '.1', 'learning_rate': '0.001', 'burn_in': '1000', 'max_batches': '500200', 'policy': 'steps', 'steps': '400000,450000', 'scales': '.1,.1'}
Traceback (most recent call last):
  File "live.py", line 131, in <module>
    model.load_state_dict(torch.load(args.weightsfile))
  File "C:\Users\xxxxxxx\.conda\envs\torchx\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\xxxxxxx\.conda\envs\torchx\lib\site-packages\torch\serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.
```

My environment is as close as I can get to what's specified in `requirements.txt`, using Python 3.7 on Windows 10 - possibly relevant is that I had to use the pycocotools version from https://github.com/philferriere/cocoapi as it doesn't seem to be available for Windows otherwise. The conda export is attached.

I've also tried with the latest available versions of all packages and get a similar result. I'd be grateful for any suggestions! Thanks.
[envexport.txt](https://github.com/michhar/pytorch-yolo-v3-custom/files/4288682/envexport.txt)

**Comment by michhar** [comment]
Hi @kittentronic!  Thanks for checking out this repo.

I do see this error when loading the original darknet `yolov3.weights` and that is because `live.py` is designed to load only PyTorch state dict weights.  We would need to convert the darknet format to PyTorch.

I am working on a script, but it will be a few days.  Also, just note, `live.py` is still under construction and I'm working to have it draw the bounding boxes correctly.

Apologize for this "WIP" and I hope you don't mind waiting a little bit longer.  Much appreciated and thanks for all of the feedback!

Best.

**Comment by kittentronic** [comment]
Thanks! Yes, I was initially taken in by the default value of `yolov3.weights` for the `weights` parameter but on comparing the code to ayooshkathuria's it became clear you're expecting a different format.

I can convert the weights file with
```
model = Darknet('cfg/yolov3.cfg')
model.load_weights('yolov3.weights')
torch.save(model.state_dict(), 'yolov3_pytorch.weights')
```
and get the code to almost run by inserting a value for `classes` into `model.net_info` after loading the model - now I'm just stuck on what looks like a CPU-versus-GPU issue...

**Comment by michhar** [comment]
@kittentronic I'm sorry to hear about cpu vs. gpu issues.  I have updated the project quite a bit.  I recommend a fresh clone.  `live.py` is getting currently updated, not entirely ready, but if you could let me know the cpu/gpu error I can take a look.  Thanks!
